---
title: "Glycaemic control in the ICU"
output: html_notebook
---


```{r}
library(data.table)
library(ggplot2)
library(magrittr)
```


```{r}

mimic_sugar = fread("../data/glycaemic_analysis_202003111632.csv")
mimic_sugar = mimic_sugar[order(icustay_id,hr)]
mimic_sugar$glucose = fcoalesce(mimic_sugar$glucose_b,
                                mimic_sugar$glucose_l)
head(mimic_sugar)
```

```{r}
pt_samp = sample(mimic_sugar$icustay_id,size = 5, replace = FALSE)
```


```{r}
cols = c("icustay_id","hr","time","glucose_b","glucose_l","insulin_amount")
mimic_sugar[icustay_id %in% pt_samp,..cols]

```

```{r}
mimic_sugar[icustay_id %in% pt_samp,] %>%
  ggplot() +
  geom_line(aes(x = hr, 
                y = glucose,
                group=icustay_id,
                col=factor(icustay_id))) +
  geom_point(aes(x = hr, 
                y = glucose,
                group=icustay_id,
                col=factor(icustay_id))) +

  coord_cartesian(xlim = c(0,12)) +
  theme(legend.position = "none")
```


```{r}
  ggplot(mimic_sugar[1:20000,]) +
  geom_line(aes(x = hr, 
                y = glucose,
                group=icustay_id),
                col="lightblue",
            alpha = 0.5) +
  geom_smooth(aes(x = hr, 
                y = glucose)) +
    coord_cartesian(xlim = c(0,12),ylim = c(0,300)) +
  theme(legend.position = "none") +
  theme_bw()

```


```{r}
mimic_sugar$time_hr = lubridate::hour(mimic_sugar$time)
mimic_sugar$time_min = lubridate::minute(mimic_sugar$time)
mimic_sugar$time_hr_min = mimic_sugar$time_hr + mimic_sugar$time_min/60
```

```{r}
pt_insulin = mimic_sugar[,.(
  mean_insulin = mean(insulin_amount,na.rm=TRUE)),
         by = icustay_id]
pt_insulin$any_insulin = !is.nan(pt_insulin$mean_insulin)
table(pt_insulin$any_insulin)
```

```{r}
insulin_pts = pt_insulin$icustay_id[pt_insulin$any_insulin]
mimic_sugar$insulin_pt = FALSE
mimic_sugar$insulin_pt[mimic_sugar$icustay_id %in% insulin_pts] = TRUE
```


```{r}
pt_samp1 = sample(mimic_sugar$icustay_id,500,replace = FALSE)
  ggplot(mimic_sugar[icustay_id %in% pt_samp1,]) +
  geom_line(aes(x = time_hr, 
                y = glucose,
                group=icustay_id),
                col="lightblue",
            alpha = 0.5) +
  geom_smooth(aes(x = time_hr, 
                y = glucose)) +
    coord_cartesian(xlim = c(0,24),ylim = c(0,300)) +
  theme(legend.position = "none") +
  theme_bw() +
  geom_hline(yintercept = 180) +
  geom_hline(yintercept = 101) +
  geom_hline(yintercept = 81)


```

```{r}
pt_samp1 = sample(mimic_sugar$icustay_id,100,replace = FALSE)

  ggplot(mimic_sugar[mimic_sugar$icustay_id %in% pt_samp1,]) +
      geom_rect(data=NULL,
            aes(xmin=0,xmax=181,ymin=-Inf,ymax=Inf),
                    fill="gray90",alpha = 0.1) +
  geom_histogram(aes(x = glucose,
                col=insulin_pt),bins=50) +
    facet_wrap(~insulin_pt,scales = "free_y",ncol=1) +
  theme(legend.position = "none") +
  theme_bw() +
  coord_cartesian(xlim = c(0,500)) +
  geom_vline(xintercept = 180) +
  geom_vline(xintercept = 101) +
  geom_vline(xintercept = 81) 


```

